
<?php
/**
 * Implements hook_help().
 */

function curso_module_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the block module.
    case 'help.page.curso_module':
      return '<p> Este es el hook_help de nuestro modulo del curso. </p>';
      // Help for another path in the block module.
  }
}



function curso_module_node_insert(\Drupal\node\NodeInterface $node)
{

  dmp("Nodo insertado con el hook hook_ENTITY_TYPE_insert()");
  dmp("Id del nodo " . $node->id());
}

function curso_module_node_update(\Drupal\node\NodeInterface $node)
{

  dump("Nodo updateado con el hook hook_ENTITY_TYPE_update()");
}
function curso_module_node_delete(\Drupal\node\NodeInterface $node)
{

  dump("Nodo deleteado con el hook hook_ENTITY_TYPE_delete()");
}


/**
 * Implements hook_theme().
 */
function curso_module_theme($existing, $type, $theme, $path)
{

  return [
    "curso_plantilla" => [
      "variables" => [
        "etiqueta" => NULL,
        "tipo" => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function curso_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{


  // if("curso_module_curso_form"==$form_id){
  //  // dump($form,"form");
  //   \Drupal::messenger()->addMessage('Entra al form alter');
  //   $form["checkbox"]["#required"] = FALSE;
  // }

  // if("node_article_form" == $form_id){
  //   \Drupal::messenger()->addMessage('Entra al form alter');
  // }

  switch ($form_id) {
    case "curso_module_form":
      $form["checkbox"]["#required"] = FALSE;
      break;
    case "node_article_form":
      break;
  }

  // function curso_module_form_curso_module_curso_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
  // {
  //  // $form["checkbox"]["#required"] = FALSE;
  // }

  // function curso_module_form_node_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
  // {
  //   // $form["checkbox"]["#required"] = FALSE;
  // }
}
