
<?php
/**
 * Implements hook_help().
 */

function curso_module_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
      // Main module help for the block module.
      case 'help.page.curso_module':
          return '<p> Este es el hook_help de nuestro modulo del curso. </p>';
      // Help for another path in the block module.
  }
}



function curso_module_node_insert(\Drupal\node\NodeInterface $node) {

  dump("Nodo insertado con el hook hook_ENTITY_TYPE_insert()");
  dump("Id del nodo ". $node->id());
}

function curso_module_node_update(\Drupal\node\NodeInterface $node) {

  dump("Nodo updateado con el hook hook_ENTITY_TYPE_update()");
}
function curso_module_node_delete(\Drupal\node\NodeInterface $node) {

  dump("Nodo deleteado con el hook hook_ENTITY_TYPE_delete()");
}


/**
 * Implements hook_theme().
 */
function curso_module_theme($existing, $type, $theme, $path) {

  return [
    "curso-plantilla"=> [
      "variables"=> [
        "etiqueta" => NULL,
        "tipo" => NULL,
        ]
      ]
  ];
}
